In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a_tensor = torch.randn(3, 4, 5)

In [3]:
# Выведите его форму (shape)
a_tensor.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
b_tensor = torch.reshape(a_tensor, (6, 10))
b_tensor.shape

torch.Size([6, 10])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементноb_tensor
v =  torch.randint(10, size=(10,)) # torch.rand(10)
v

tensor([8, 7, 7, 0, 6, 3, 7, 6, 8, 7])

In [6]:
torch.mul(b_tensor, v)

tensor([[ 15.3655,  -1.0972,   7.2591,   0.0000,   3.7778,  -1.3586,  -8.4338,
          -9.4676,   5.2074,  -2.5139],
        [ -0.7843,   7.2709,   0.4918,  -0.0000,  -5.9739,   2.2550,  -4.2932,
          -0.4424,  18.6472,  -5.6874],
        [  9.3941,  -8.1151,   9.1934,   0.0000,   3.6328,  -0.2685,  -5.1515,
          -0.1869,  -5.5777,   4.1045],
        [ -2.4800,  -2.0651,   7.9070,  -0.0000,  -4.4651,   1.4971,  -3.6172,
          -6.8984,  -4.3451,  -3.1176],
        [  4.6689,  -5.0307, -11.8382,   0.0000,   8.5578,  -2.0026,   4.7787,
          -5.1266,   0.8188,   2.4998],
        [ -1.5116,  -0.8708,  -3.9191,  -0.0000,   2.3618,  -2.4232,   6.7362,
           8.0272,  -1.3014,   1.8347]])

In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
b_tensor.mm(b_tensor.reshape(10, 6))

tensor([[ 10.0170,  -0.7921,  -1.0095,   3.3558,  -0.2878,  -0.9219],
        [ -4.0481,   1.0734,   0.0150,  -1.6243,  -2.8575,  -8.5291],
        [  5.9216,   0.1025,   0.2598,   3.3336,   0.2069,   2.2177],
        [ -2.6488,   0.8041,  -4.1583,   2.2323,  -3.5983,   2.1118],
        [  5.6009,   0.6112,  -0.5326,   0.6573,   1.4768,  -0.1455],
        [-11.6978,   3.6089,  -3.9185,   4.4169,  -3.1314,  -3.3235]])

In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1, 0.5, 2], requires_grad=True)
z = x**3 + x - 75*x
z.backward(x)
x.grad

tensor([ -71.0000,  -36.6250, -124.0000])

In [9]:
# Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))

In [10]:
# Переведите его в формат numpy
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте
from torch.autograd import Variable


def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 120
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%10:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 11, x = 1.69, y = 4.12
Iteration 21, x = 1.55, y = 3.92
Iteration 31, x = 1.47, y = 3.85
Iteration 41, x = 1.42, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 101, x = 1.34, y = 3.81
Iteration 111, x = 1.34, y = 3.81
